export interface SanPham {
    id : string,
    tenSanPham : string,
    nhanHieu : string,
    baoHanh : string,
    tomTat : string,
    phuKien : string,
    cauHinh : string,
    gia : number,
    thongTin : string,
    chiTiet : string,
    thongSo : string,
    anh1 : string,
    anh2 : string,
    anh3 : string,
    anh4 : string,
    soLuong : number,
    danhMuc : string,
}